# Generated by Django 6.0.6 on 2026-06-09 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areainteres',
            options={'verbose_name': 'Área de Interés', 'verbose_name_plural': 'Áreas de Interés'},
        ),
        migrations.AlterModelOptions(
            name='tipooportunidad',
            options={'verbose_name': 'Tipo de Oportunidad', 'verbose_name_plural': 'Tipos de Oportunidades'},
        ),
        migrations.AlterField(
            model_name='talent',
            name='cv',
            field=models.FileField(upload_to='cvs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
