# Generated by Django 6.0.5 on 2026-05-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('degree', models.CharField(help_text='Ej: Ingeniería en Computación', max_length=100, verbose_name='Carrera')),
                ('university', models.CharField(default='ESPOL', max_length=100, verbose_name='Universidad')),
                ('skills', models.TextField(help_text='Separadas por comas (Ej: Python, Django, Liderazgo)', verbose_name='Habilidades Clave')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Perfil de LinkedIn')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='GitHub / Portafolio')),
                ('cv', models.FileField(upload_to='cvs/', verbose_name='Curriculum Vitae')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
